name: livescore
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  floating_navbar: ^2.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.6
  http: ^1.1.0
  iconly: ^1.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/categories/
    - assets/images/categories_title/
    - assets/images/clubs/
    - assets/images/dummy/
    - assets/images/illustrations/
    - assets/images/regions/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
