// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMN8J4Kf9nrR-cvg-fnszE-xCTkXgJDDA',
    appId: '1:79208154692:web:b06ddc5b9ad213af5bde11',
    messagingSenderId: '79208154692',
    projectId: 'livescore-a3917',
    authDomain: 'livescore-a3917.firebaseapp.com',
    storageBucket: 'livescore-a3917.appspot.com',
    measurementId: 'G-2LB0KP8XPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLtGJdjYgsI22tBJp2QSV5rQ_ipEwU5I',
    appId: '1:79208154692:android:599e2f584cf513285bde11',
    messagingSenderId: '79208154692',
    projectId: 'livescore-a3917',
    storageBucket: 'livescore-a3917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8zr-9AamyVsyfd5Iy7gPQMjefRTNFwgg',
    appId: '1:79208154692:ios:0e4067a970303fa15bde11',
    messagingSenderId: '79208154692',
    projectId: 'livescore-a3917',
    storageBucket: 'livescore-a3917.appspot.com',
    iosBundleId: 'com.example.livescore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8zr-9AamyVsyfd5Iy7gPQMjefRTNFwgg',
    appId: '1:79208154692:ios:b0e1ef646b403b505bde11',
    messagingSenderId: '79208154692',
    projectId: 'livescore-a3917',
    storageBucket: 'livescore-a3917.appspot.com',
    iosBundleId: 'com.example.livescore.RunnerTests',
  );
}
